const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const page=await browser.newPage({viewport:{width:1365,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto('http://127.0.0.1:8766/');
  await page.waitForFunction(()=>document.getElementById('connection').textContent.length>0);
  await page.selectOption('#source','fixture');
  await page.getByRole('button',{name:'주차되면 좋은 카페 ↗'}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 결과를 확인해 주세요.');
  assert.ok(await page.locator('.card').count()>0);
  const trace=JSON.parse(await page.locator('#trace').textContent());
  assert.equal(trace.request.spatial.radius_m,3000);
  assert.equal(trace.response.lenses[0].applied.parking,true);
  assert.equal(await page.locator('.marker').count(),await page.locator('.card').count());
  await page.locator('#dogs-button').click();
  assert.equal(await page.locator('#dogs-dialog input[type=number]').count(),0);
  await page.getByLabel('보리',{exact:true}).check();
  await page.getByLabel('초코',{exact:true}).check();
  await page.getByRole('button',{name:'완료',exact:true}).click();
  await page.waitForFunction(()=>{try{return JSON.parse(document.getElementById('trace').textContent).response.request.dogs.length===2;}catch{return false;}});
  const dogs=JSON.parse(await page.locator('#trace').textContent()).request.dogs;
  assert.deepEqual(dogs.map(d=>d.dog_weight_kg),[5,30]);
  assert.ok(dogs.every(d=>d.revision==='2026-09-06T00:00:00Z'&&d.dog_size===null));
  await page.locator('.card-head').first().click();
  assert.equal(await page.locator('.dog-evaluation').count(),2);
  assert.ok(!(await page.locator('#cards').textContent()).includes('undefined'));
  await page.locator('#radius').click();
  await page.getByRole('button',{name:'10km',exact:true}).click();
  await page.waitForFunction(()=>{try{return JSON.parse(document.getElementById('trace').textContent).response.request.spatial.radius_m===10000;}catch{return false;}});
  await page.getByRole('button',{name:'동물병원',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 조건을 더 구체적으로 알려 주세요.');
  assert.equal(await page.locator('.card').count(),0);
  await page.getByRole('button',{name:'전체보기',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 결과를 확인해 주세요.');
  await page.getByRole('button',{name:'주차 필수 카페 ↗'}).click();
  await page.waitForFunction(()=>!document.getElementById('search-form').hasAttribute('aria-busy'));
  assert.equal(await page.locator('.card').count(),0);
  await page.getByRole('button',{name:'조용하면 좋은 카페 ↗'}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 결과를 확인해 주세요.');
  assert.ok((await page.locator('#signals').textContent()).includes('조용'));
  await page.getByRole('button',{name:'싼 카페 ↗'}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 조건을 더 구체적으로 알려 주세요.');
  assert.equal(await page.locator('.card').count(),0);
  assert.ok(await page.locator('#signals button:disabled').count()>0);
  const firstSelection=JSON.parse(await page.locator('#trace').textContent()).response;
  await page.getByRole('button',{name:'가까운 곳',exact:true}).click();
  await page.waitForFunction(()=>{try{return JSON.parse(document.getElementById('trace').textContent).response.revision===2;}catch{return false;}});
  const refined=JSON.parse(await page.locator('#trace').textContent()).response;
  assert.deepEqual(refined.request,firstSelection.request);
  assert.equal(refined.search_id,firstSelection.search_id);
  assert.equal(refined.signals[0].selected_option_id,'cost.travel_distance');
  assert.ok(await page.locator('.card').count()>0);
  // Simulate losing the response after the server already committed confirmation.
  const actions=[];
  page.on('request',req=>{if(req.url().endsWith('/api/fixture/actions'))actions.push(req.postDataJSON());});
  await page.route('**/api/fixture/actions',async route=>{
    const committed=await route.fetch();assert.equal(committed.status(),200);
    await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'응답을 확인하지 못했어요.'})});
  });
  await page.getByRole('button',{name:'이 방향으로 검색',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('status').classList.contains('error'));
  await page.unroute('**/api/fixture/actions');
  await page.getByRole('button',{name:'다시 시도',exact:true}).click();
  await page.waitForFunction(()=>{try{return JSON.parse(document.getElementById('trace').textContent).response.revision===3;}catch{return false;}});
  assert.deepEqual(actions[0],actions[1]);
  const confirmed=JSON.parse(await page.locator('#trace').textContent()).response;
  assert.equal(confirmed.confirmed_lens_id,refined.lenses[0].id);
  assert.deepEqual(confirmed.request.dogs,firstSelection.request.dogs);
  assert.equal(await page.getByRole('button',{name:'선택한 검색 방향 ✓',exact:true}).isDisabled(),true);
  // A changed query invalidates an action already in flight.
  await page.getByRole('button',{name:'싼 카페 ↗'}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 조건을 더 구체적으로 알려 주세요.');
  await page.route('**/api/fixture/actions',async route=>{await new Promise(r=>setTimeout(r,350));await route.continue().catch(()=>{});});
  await page.getByRole('button',{name:'가까운 곳',exact:true}).click();
  await page.locator('#query').fill('카페');
  await page.waitForTimeout(500);
  assert.equal(await page.locator('.card').count(),0);
  await page.unroute('**/api/fixture/actions');
  // Deliberately delay an old response and change modes while it is in flight.
  await page.route('**/api/fixture/ai',async route=>{await new Promise(r=>setTimeout(r,350));await route.continue().catch(()=>{});});
  await page.getByRole('button',{name:'검색 실행',exact:true}).click();
  await page.getByRole('button',{name:'AI 조건 검색 전환',exact:true}).click();
  await page.waitForTimeout(500);
  assert.equal(await page.locator('.card').count(),0);
  await page.unroute('**/api/fixture/ai');
  await page.locator('#query').fill('알베르');
  await page.getByRole('button',{name:'검색 실행',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('status').textContent==='검색 결과를 확인해 주세요.');
  assert.equal(await page.locator('.card').count(),1);
  await page.locator('.card-head').first().click();
  const dir=path.join(__dirname,'screenshots');fs.mkdirSync(dir,{recursive:true});
  await page.screenshot({path:path.join(dir,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(dir,'mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  // Missing live credentials must produce an error, never fixture results.
  await page.selectOption('#source','live');
  await page.getByRole('button',{name:'AI 조건 검색 전환',exact:true}).click();
  await page.locator('#query').fill('카페');
  await page.route('**/api/live/ai',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'개발 API 주소가 설정되지 않았어요.'})}));
  await page.getByRole('button',{name:'검색 실행',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('status').classList.contains('error'));
  assert.equal(await page.locator('.card').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS: AI search, bundled dogs, filters, refinement, confirmation, lost-response retry, stale action, unsupported options, normal search, responsive layout, live failure.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
